version: '3.3'

services:
  web:
    build: ./app
    command: python manage.py runsslserver 0.0.0.0:8001 --settings=come_together.settings
    stdin_open: true
    tty: true
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
      - 587:587
    env_file: .envdev
    environment:
      - COMPOSE_HTTP_TIMEOUT=600
      - SQL_ENGINE=django.db.backends.postgresql
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .envdevdb
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file: .pgadmindev
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:8001"
  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
          - esdata:/usr/share/elasticsearch/data
volumes:
  postgres_data:
  esdata:
  pgadmin:
