version: '3.3'

services:
  web:
    container_name: gallop_web
    build: ./app
    command: python manage.py runsslserver 0.0.0.0:8001 --settings=gallop.settings
    stdin_open: true
    tty: true
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
      - 587:587
    env_file: ./env/dev/.env
    depends_on:
      - db
      - rabbitmq
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - TZ=Europe/Warsaw
  db:
    container_name: gallop_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env/dev/.envdb
  pgadmin:
    container_name: gallop_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file: ./env/dev/.pgadmin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:8001"
  celery:
    build: ./app
    command: celery -A gallop worker -l debug
    volumes:
      - ./app/:/usr/src/app/
    links:
      - redis
    environment:
      - TZ="Europe/Warsaw"
    depends_on:
      - db
      - redis
      - rabbitmq
  celery-beat:
    build: ./app
    command: celery -A gallop beat -l debug
    volumes:
      - ./app/:/usr/src/app/
    links:
      - redis
    environment:
      - TZ="Europe/Warsaw"
    depends_on:
      - db
      - redis
      - rabbitmq
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - TZ=Europe/Warsaw
  elasticsearch:
    container_name: gallop_elasticsearch
    image: launcher.gcr.io/google/elasticsearch2
    environment:
      - TZ="Europe/Warsaw"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
          - esdata:/usr/share/elasticsearch/data
volumes:
  postgres_data:
  esdata:
  pgadmin:
