version: '3.3'

services:
  web:
    build: ./app
    command: python manage.py runsslserver 0.0.0.0:8001
    stdin_open: true
    tty: true
    volumes:
      - ./app/:/usr/src/app/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - 8001:8001
      - 587:587
      - 465:465
      - 25:25
    env_file: .envdev
    environment:
      - COMPOSE_HTTP_TIMEOUT=600
      - DEBUG=1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - TZ=Europe/Warsaw
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .envdevdb
  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
          - esdata:/usr/share/elasticsearch/data
volumes:
  postgres_data:
  esdata:
