version: '3.3'

services:
  web:
    container_name: gallop_web
    build: ./app
    command: python manage.py runsslserver 0.0.0.0:8001 --settings=gallop.settings
    stdin_open: true
    tty: true
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
    env_file: ./env/dev/.env
    depends_on:
      - db
      - rabbitmq
      - redis
  redis:
    image: redis:latest
    environment:
      - TZ=Europe/Warsaw
  flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://rabbitmq", "--port=8888"]
    depends_on:
      - celery
    ports:
      - 8888:8888
  db:
    container_name: gallop_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env/dev/.env
  pgadmin:
    container_name: gallop_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file: ./env/dev/.pgadmin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:8001"
  celery:
    build: ./app
    command: celery -A gallop worker -l debug
    links:
      - redis
    env_file: ./env/dev/.env
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
      - redis
      - rabbitmq
  celery-beat:
    build: ./app
    command: celery -A gallop beat -l debug --pidfile=
    volumes:
      - ./app/:/usr/src/app/
    links:
      - redis
    env_file: ./env/dev/.env
    depends_on:
      - db
      - redis
      - rabbitmq
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - TZ=Europe/Warsaw
  elasticsearch:
    container_name: gallop_elasticsearch
    image: blacktop/elasticsearch:7.7
    environment:
      - TZ="Europe/Warsaw"
    volumes:
          - esdata:/usr/share/elasticsearch/data
volumes:
  postgres_data:
  esdata:
  pgadmin:
